print('Hello, World!')
print('Welcome to Python programming.')
print('This is a simple Python script.')
print('You can run this script to see the output.')
print('Python is a versatile language.')
print('You can use it for web development, data analysis, and more.')
print('Have fun learning Python!')